name: Pull Request checks

on:
  workflow_call:
    inputs:
      configs-path:
        description: 'Set this to override the linting configs with the ones in this folder. 
        The structure inside of the folder must be the same as the one in this repository.'
        required: false
        type: string
        default: '._linting' # Use the configs from this repository (separate checkout)
      excluded-directories:
        description: 'List of directories to exclude (JSON), empty = none'
        required: false
        type: string
        default: '[]'

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: eslint
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changedFiles
        uses: tj-actions/changed-files@v34
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      # Needed to have access to the linter files
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: pmagentur/linting-javascript@master
          path: ._linting

      # Setup node packages required for linter step
      - name: Node CI
        id: nodeCI
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install --prefix ._linting

      - name: Linting with eslint
        id: linter
        uses: pmagentur/linting-action@v0.4
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "._linting/node_modules/.bin/eslint -c ${{ inputs.configs-path }}/.eslintrc.json {files} -f unix --no-eslintrc --quiet"
          parse-pattern: '(?<file>[^:]+):(?<line>\d+)(?::(?<column>\d+))?: (?<message>.+) \[(?<level>[^\/]+)\/(?<ruleName>[^\]]+)\]'
          relevant-file-endings: '["js", "ts"]'
          excluded-directories: ${{ inputs.excluded-directories }}

      - name: Add Annotations
        uses: pmagentur/linting-annotations@v0.1
        if: failure() && steps.linter.outputs.annotations != ''
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          checkName: 'JavaScript Linting'
          annotations: ${{ steps.linter.outputs.annotations }}
